name: JukeBukkit
main: cc.thedudeguy.jukebukkit.JukeBukkit
version: 1.0
description: Allows you to "Burn" new music onto Music Discs and play them in the Jukeboxes.
author: Chris Churchwell (thedudeguy)
website: http://dev.bukkit.org/server-mods/jukebukkit/
depend: [Spout]